version: '3'

services:
  postgres:
    container_name: postgres-laborexchange
    image: postgres:16.1
    environment:
      POSTGRES_DB: "labor-exchange"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
    # поменял порт, т.к. если в системе установлен postgres (как у меня), то стандартный порт будет занят
      - "8503:5432"
    restart: unless-stopped
volumes:
    postgres: