"""The unique constraint added for a Response table

Revision ID: b1bc2f0a7a01
Revises: 272a94fcabff
Create Date: 2024-01-24 16:07:49.008839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1bc2f0a7a01'
down_revision = '272a94fcabff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('response_unique_key', 'responses', ['user_id', 'job_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('response_unique_key', 'responses', type_='unique')
    # ### end Alembic commands ###
