"""added the ondelete condition

Revision ID: a316eeaaebe1
Revises: 3f5a681617e5
Create Date: 2024-01-25 20:10:52.202074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a316eeaaebe1'
down_revision = '3f5a681617e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('responses_job_id_fkey', 'responses', type_='foreignkey')
    op.drop_constraint('responses_user_id_fkey', 'responses', type_='foreignkey')
    op.create_foreign_key(None, 'responses', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'responses', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'responses', type_='foreignkey')
    op.drop_constraint(None, 'responses', type_='foreignkey')
    op.create_foreign_key('responses_user_id_fkey', 'responses', 'users', ['user_id'], ['id'])
    op.create_foreign_key('responses_job_id_fkey', 'responses', 'jobs', ['job_id'], ['id'])
    # ### end Alembic commands ###
