"""Add a new column for a user table

Revision ID: 3f5a681617e5
Revises: b1bc2f0a7a01
Create Date: 2024-01-25 17:37:37.774705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f5a681617e5'
down_revision = 'b1bc2f0a7a01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_refresh_token', sa.String(), nullable=True, comment='Хэш refresh-токена'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_refresh_token')
    # ### end Alembic commands ###
